# docker-compose.yml

services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server